name: network_data_transfer
description: A network data transfer package
repository: https://github.com/ominibyte/network_data_transfer

version: 0.0.1-dev.1

environment:
  sdk: ">=2.3.1 <3.0.0"

dev_dependencies:
  test: ^1.15.2